dist: trusty
sudo: required
language: bash
services:
- docker
env:
  matrix:
  - IMAGE_SUFFIX=nginx DOCKER_BUILD_ARGS="nginx"
  - IMAGE_SUFFIX=server DOCKER_BUILD_ARGS="server"
  - IMAGE_SUFFIX=client DOCKER_BUILD_ARGS="client"
  - IMAGE_SUFFIX=export DOCKER_BUILD_ARGS="export"
  global:
  - IMAGE_PREFIX="orihoch/beit-hatfutsot-gentrees-app-"
script:
- bash .travis.sh script
deploy:
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
